import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={outfit.className}>
        <div>
          <Header />
          <div className=" px-4 md:px-16">
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
